### ISSUE TITLE
[meta] MVP + Product Plan

### ISSUE THREAD

**Issue by maxhniebergall** [maxhniebergall/Aphori.st#8]
# MVP
- [ ] Able to view posts & comments
- [ ] Account creation
  - [ ] https + auth token
- [ ] Able to post posts
- [ ] Able to comment
- [ ] Performant (caching + compression)

# Production Product Plan
- [ ] Combine/link similar posts/comments
- [ ] Multiple Sorting Options

**Comment by maxhniebergall** [comment]
consider switching to react-vtree https://www.npmjs.com/package/react-vtree
